In [40]:
from sklearn import metrics
import numpy as np
import pandas as pd
import pickle
import re
import mymodule

In [29]:
with open('model/lda_model.pkl', 'rb') as f:
  lda_model = pickle.load(f) #import lda model
  
data = pd.read_csv('dataset/DatasetLegal.csv') #read data

with open('model/topic_dict.pkl', 'rb') as f:
    topic_dict = pickle.load(f)

In [9]:
str_answer = data['answer'].astype(str)
str_answer = str_answer.map(lambda x: re.sub('[,\.!?#]', '', x))
corpus = [mymodule.preprocess(text) for text in str_answer]
predicted_labels = [max(lda_model[text], key=lambda x: x[1])[0] for text in corpus]

In [30]:
print(predicted_labels[:10])
pred_topic = [topic_dict.get(topic) for topic in predicted_labels]
print(pred_topic[:10])

[1, 3, 0, 6, 0, 4, 0, 4, 6, 4]
['family', 'children', 'contract', 'succession', 'contract', 'sentence', 'contract', 'sentence', 'succession', 'sentence']


In [31]:
test = data['Classes']
test

0         family
1         family
2       contract
3         family
4       contract
          ...   
7026    contract
7027    contract
7028    criminal
7029    criminal
7030    contract
Name: Classes, Length: 7031, dtype: object

In [34]:
y_test_pred = pred_topic
y_test = test

In [35]:
metrics.accuracy_score(y_test, y_test_pred)

0.4667899303086332

In [38]:
metrics.confusion_matrix(y_test, y_test_pred)

array([[   0,    1,   19,    0,   32,    4,    5,  317,    4],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,   94, 2044,    0,    8,   33,  149,  158,   48],
       [   0,    6,    8,    0,   14,    7,   32,  987,    2],
       [   0,  538,   34,    0,  464,    5,   11,   67,  995],
       [   0,    2,   14,    0,    4,  774,  145,    5,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int64)

In [41]:
metrics.precision_recall_fscore_support(y_test, y_test_pred)

c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(array([0.        , 0.        , 0.96460595, 0.        , 0.88888889,
        0.94046173, 0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.80662983, 0.        , 0.21948912,
        0.81904762, 0.        , 0.        , 0.        ]),
 array([0.        , 0.        , 0.87857296, 0.        , 0.35204856,
        0.87556561, 0.        , 0.        , 0.        ]),
 array([ 382,    0, 2534, 1056, 2114,  945,    0,    0,    0], dtype=int64))

In [49]:
accuracy = metrics.accuracy_score(y_test, y_test_pred)
precision = metrics.precision_score(y_test, y_test_pred, average='weighted')
recall = metrics.recall_score(y_test, y_test_pred, average='weighted')
f1 = metrics.f1_score(y_test, y_test_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Accuracy: 0.4667899303086332
Precision: 0.7413111803844005
Recall: 0.4667899303086332
F1-score: 0.5401712480059311


c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
